### ISSUE TITLE
Does JITCSDE supports the case where g(t,y) is a matrix and with multiple noise sources?

### ISSUE THREAD

**Issue by hubhubhang** [neurophysik/jitcsde#1]
Dear developer, 

I would like to ask if JITCSDE supports the case where g(t,y) is a matrix? Also the case with multiple noise sources? Explicitly, I am trying the implement the equation in the below form:

![image](https://user-images.githubusercontent.com/13278555/46236253-bf4bd800-c332-11e8-95dc-c08d7bd642ad.png)

It will be great if there is such a feature. 

Thank you,
Herman

**Comment by Wrzlprmft** [comment]
I am not exactly sure how to interpret your equation, so I will address all the issues separately:

* Having a matrix-valued phase space is no problem as it can be transformed to a vector-valued phase space easily. You only need to keep track of the indices yourself.

* If I am not mistaken, the sum of two Wiener processes is again a Wiener process. Hence, there should be no need for a second matrix. You could just use one matrix with sqrt(g₁²+h₁²) and so on as coefficients. (Please verify all of this; I just pulled this out of the back of my head.)

* If you have an actual matrix–vector multiplication in your noise term, e.g., your noise term is *g*·d*W*, where *g*∊ℝ<sup>2×2</sup> and *W*∊ℝ², you can try to make a linear coordinate transformation such that *g* is diagonalised. JiTCSDE doesn’t support this natively since the underlying integration algorithm doesn’t and it was made with large systems in mind, where such a case usually doesn’t arise.

**Comment by hubhubhang** [comment]
Thank you for your quick response.

The equations I am trying to implement are in the below form:
 d**y** = **f**(t, **y**) dt + G(t, **y**) **dW**

where **y**, **f**, **dW** are vectors and G(t, **y**) is a matrix and G(t, **y**) **dW** is calculated by the usual matrix-vector multiplication. More explicitly, they are 
dy<sub>1</sub>=f<sub>1</sub>dt + g<sub>1</sub> dW<sub>1</sub> + h<sub>1</sub> dW<sub>2</sub>
dy<sub>2</sub>=f<sub>2</sub>dt + g<sub>2</sub> dW<sub>1</sub> + h<sub>2</sub> dW<sub>2</sub>
dy<sub>3</sub>=f<sub>3</sub>dt + g<sub>3</sub> dW<sub>1</sub> + h<sub>3</sub> dW<sub>2</sub>
dy<sub>4</sub>=f<sub>4</sub>dt + g<sub>4</sub> dW<sub>1</sub> + h<sub>4</sub> dW<sub>2</sub>

In my actual code, the subscript for y, f, g, h is a large number.

The problem I found when transforming the matrix-valued phase space to the vector-valued one is that now I have the same noise term dW<sub>1</sub> for g<sub>1</sub>, g<sub>2</sub>, g<sub>3</sub>, g<sub>4</sub>, but the current JITCSDE only support the case where each g<sub>1</sub>, g<sub>2</sub>, g<sub>3</sub>, g<sub>4</sub> has a different noise term associated with them. 

The diagonalization of G doesn't work in my case, so I wonder if there is an option in JITCSDE such that I can control the value of the **dW** vector? For example, restricting all the elements of **dW** to be the same in each iteration of d**y** .

I will verify your suggestion for the multiple noise source and get back to you, but it seems to me that certain condition for g<sub>i</sub> and h<sub>i</sub> has to be satisfied in order for this to work.

Thank you again.

**Comment by Wrzlprmft** [comment]
Sorry, but I still do not get what your setup is. In your second set of equations, were does the *h* come from? If this is an example for *y*∈ℝ⁴, why does d*W* only have two components?

That being said, two remarks:

* If *g* depends on the state and time, the entire diagonalisation approach very likely becomes impossible (unless the dependence is just a constant factor to all components or such).

* Making two components of d*W* equal is theoretically possible and may even be technically easy. I will look into this once you are sure that this really solves your problem.

**Comment by hubhubhang** [comment]
Those h<sub>i</sub> follow from the definition I have in my first message. The notation should be better if I replace g<sub>i</sub> and  h<sub>i</sub> by  G<sub>ij</sub>. So it basically follows the definition in section 3.8.2 of "Stochastic Processes for Physicists" by Kurt Jacobs.

![ito](https://user-images.githubusercontent.com/13278555/46260837-33f05500-c4a0-11e8-9676-da15b0664782.PNG)

The eqn I am implementing follow this form and thus **x** and **dW** doesn't necessarily to have the same dimension (see (3.82)).
So, in my case, it's 

dx<sub>1</sub> = f<sub>1</sub> dt + G<sub>11</sub> dW<sub>1</sub> + G<sub>12</sub> dW<sub>2</sub>
dx<sub>2</sub> = f<sub>2</sub> dt + G<sub>21</sub> dW<sub>1</sub> + G<sub>22</sub> dW<sub>2</sub>
dx<sub>3</sub> = f<sub>3</sub> dt + G<sub>31</sub> dW<sub>1</sub> + G<sub>32</sub> dW<sub>2</sub>
dx<sub>4</sub> = f<sub>4</sub> dt + G<sub>41</sub> dW<sub>1</sub> + G<sub>42</sub> dW<sub>2</sub>

Yes, I suspect it should be technically easy too. It will be great if it can be done. Thanks.

**Comment by Wrzlprmft** [comment]
I understand now. In your case, the following should work:

1. Complement your matrix *G* with ones on the diagonal (or arbitrary non-zero numbers in arbitrary places) to obtain a square matrix *Ǧ.*
2. Find an invertible transformation *T* that diagonalises *Ǧ.*
3. Apply *T* to your differential equations. You should now end up with two differential equations with a only one noise term (d*W*₁ or d*W*₂) and two without a noise term.
4. The resulting differential equations should be solvable with JiTCSDE.
5. Apply *T⁻¹* to the solutions.

Two caveats:

* I haven’t thoroughly checked this procedure. Please verify that it does what I claim it does.
* As mentioned before, all of this will become difficult or impossible if *G* depends on state and time as you need to find a transformation that works all the time.

Sidenote (that does not apply to you but possibly to future readers): Any case with identical noise terms in different differential equations is a special case of the above. You just have to write down the respective matrix *G* that “copies” the noise term to a different equation.

**Comment by hubhubhang** [comment]
Sorry, I am working on other stuff. Will come back to verify your suggestion in a few weeks. But my system is very large and the matrix G does depends on state and is not diagonalizable.

**Comment by Wrzlprmft** [comment]
> But my system is very large and the matrix G does depends on state and is not diagonalizable.

In that case, I am afraid I cannot help you.
