### ISSUE TITLE
"Symbol not found" error on complex SDEs, works with simple

### ISSUE THREAD

**Issue by jajcayn** [neurophysik/jitcsde#2]
Dear developer,
I got myself into a peculiar situation where `jitcsde` works on a simple system (posted below), but not for more complex SDEs (34 variables - computational neuroscience is my field). 

In a simple system example I am simply adding Gaussian White noise as
```python
g = [0., 0., 0., 4.04]
ODE = jitcsde(self.full_system, g)
```
so the idea is that 4th state variable is driven by `N(0. 4.04)` hence GWN with variance 4.04. When I compile and run the integrator, I got a satisfactory output, everything as expected.

However, when I try to do the same thing on my complex thalamo-cortical model with 34 variables, I encounter an error:
```
/var/folders/2q/q8mj2sqx5yj82b2t14j14rq40000gn/T/tmpjz6r0l5s/jitced.c:230:17: warning: comparison of integers of different signs: 'int' and 'unsigned int' [-Wsign-compare]
        for (int i=0; i<number; i++)
                      ~^~~~~~~
1 warning generated.
Traceback (most recent call last):
  File "20191013-Schellenberger_manual/simulation.py", line 191, in <module>
    main()
  File "20191013-Schellenberger_manual/simulation.py", line 183, in main
    t_stop=100.0, dt=1e-4, t_spin_up=0.0, sampling_dt=1e-2, solver="Radau"
  File "20191013-Schellenberger_manual/simulation.py", line 115, in run
    times=time_array.time_vector, method=solver
  File "/Users/nikola/work-brain/sleep_rhythms/code/model_definitions/Schellenberger_thalamo_manual/integrator.py", line 160, in solve
    extra_compile_args=self.extra_compile_args, omp=(["-fopenmp"], [])
  File "/Users/nikola/.virtualenvs/sleepy3/lib/python3.7/site-packages/jitcsde/_jitcsde.py", line 428, in compile_C
    self._compile_and_load(verbose,extra_compile_args,extra_link_args,omp)
  File "/Users/nikola/.virtualenvs/sleepy3/lib/python3.7/site-packages/jitcxde_common/_jitcxde.py", line 308, in _compile_and_load
    self.jitced = find_and_load_module(self._modulename,self._tmpfile())
  File "/Users/nikola/.virtualenvs/sleepy3/lib/python3.7/site-packages/jitcxde_common/modules_35.py", line 33, in find_and_load_module
    module = module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: dlopen(/var/folders/2q/q8mj2sqx5yj82b2t14j14rq40000gn/T/tmpjz6r0l5s/jitced.cpython-37m-darwin.so, 2): Symbol not found: ___kmpc_dispatch_init_4
  Referenced from: /var/folders/2q/q8mj2sqx5yj82b2t14j14rq40000gn/T/tmpjz6r0l5s/jitced.cpython-37m-darwin.so
  Expected in: flat namespace
 in /var/folders/2q/q8mj2sqx5yj82b2t14j14rq40000gn/T/tmpjz6r0l5s/jitced.cpython-37m-darwin.so
```

Note, if I omit the noise completely in my complex system, I am able to perform a successful integration using `jitcode` with:
```python
ode_system = jitcode(self.full_ode_system)
ode_system.generate_jac_C(do_cse=True)
ode_system.compile_C(
    extra_compile_args=self.extra_compile_args, omp=(["-fopenmp"], [])
)
...
```
while in the noise case I simply do
```python
ode_system = jitcsde(self.full_ode_system, noise)
ode_system.compile_C(
    extra_compile_args=self.extra_compile_args, omp=(["-fopenmp"], [])
)
```

(the `self. self.extra_compile_args ` is just a list with compiler args as I'm on a MacOS and need to point the compiler to llvm's clang with OpenMP support).

Do you have any idea or hunch what can be the culprit? Is the system's complexity a problem? Am I omitting some steps while initializing the compiler?

**Comment by jajcayn** [comment]
resolved. Not sure why, but I was compiling the system with `omp=(["-fopenmp"], [])` it did throw an error, but simply putting `omp=False` the system now compiles OK. Closing the issue.

**Comment by Wrzlprmft** [comment]
This is a problem with the Open MP libraries, not with JiTCSDE. If you search the Internet for your error message, you will find other people having similar problems without JiTC*DE.

The reason why you do not see it for smaller systems is probably that your `chunk_size` is larger than the dynamics and thus there is nothing to parallelise. This also explains why the problem vanishes if you select `omp=False`, i.e., deactivate Open MP. This naturally is somewhat dissatisfying.

Since I cannot reproduce the problem, I can only give a few hints regarding the approach. You might try different compiler and linker arguments for Open MP (i.e., the first and second entry of the `omp` argument). Another approach would be to first try to successfully compile a simple OpenMP example and then use the successful compiler and linker arguments. The advantage of the latter approach is that it is easier to get help from Open MP experts.
