### ISSUE TITLE
using on SLURM return Illegal instruction  (core dumped) 

### ISSUE THREAD

**Issue by Ziaeemehr** [neurophysik/jitcsde#4]
Hello,

When I try to use Jitcsde on a system with slurm I got the following error:

```sh
/var/spool/slurmd/job2713947/slurm_script: line 12: 265387 Illegal instruction     (core dumped) python3 -W ignore single_job.py
```
code run without error on the same machine without slurm queue.
Probably the code is compiling with avx instructions and that node doesn't support avx
In our cluster, the head node is more recent than the computational nodes, 
I google it, people suggest compiling the code with  `-march=native -mavx ` on head node.

I don't know how. 
like this?

```python
I.compile_C(omp=self.use_omp, extra_compile_args=["march=native -mavx"]
```

please let me know if you have a solution.
the issue is resolved if I try to compile the code for every single run, which is not efficient.

**Comment by Wrzlprmft** [comment]
Your code achieves that JiTCSDE compiles with `-march=native -mavx` and **only** those flags. This means that you use a few compiler flags that JiTC*DE uses by default and which may be beneficial, in particular general optimisation. You can find the default flags in `jitcxde_common.DEFAULT_COMPILE_ARGS`.

Moreover, the flags you use do not disable AVX but explicitly enable it. The flag that disables AVX is `-mno-avx`. Also, `march=native` generally optimises the compilation to the compiling machine’s instruction set, whereas something like `-march=x86_64` produces a more flexible output. Ideally, whoever runs your cluster can tell you a suitable list of flags that work on every machine.

I would suggest to start with something like this:

``` Python3
from jitcxde_common import DEFAULT_COMPILE_ARGS
[…]
I.compile_C( extra_compile_args = DEFAULT_COMPILE_ARGS + ["-mno-avx"] )
```

This keeps the default compiler arguments, but disables AVX.
